---
- name: Update ubuntu
  apt: update_cache=yes

- name: Install a .deb package from the internet.
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Adding user {{ user }} to docker group
  user: 
    name: "{{ user }}"
    group: docker
    shell: /bin/bash
    groups: docker
    append: yes

- name: Restart service docker
  service:
    name: docker
    state: started

- name: Reboot and wait for reboot to complete
  reboot: