---
- name: Setting up master node
  hosts:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
  user: vagrant
  become: true
  roles: 
    - basic
  vars:
    cron_user: vagrant