- name: Create a slave MPI user
  user:
    name: "{{ mpi_user_name }}"
    password: "{{ mpi_user_name | password_hash('sha512') }}"
    state: present
    shell: /bin/bash       
    system: no             
    createhome: yes        
    home: /home/{{ mpi_user_name }}

- name: Mount nfs directories
  # become: yes
  # become_user: "{{ mpi_user_name }}"
  mount:
    fstype: "{{ item.type }}"
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    state: mounted
  with_items: "{{ nfs_imports }}"

# - name: Creating /etc/fstab file.
#   become: yes
#   become_user: "{{ mpi_user_name }}"
#   template:
#     src: fstab.j2
#     dest: /etc/fstab
#     owner: root
#     group: root
#     mode: 0644
