---
- name: Update ubuntu
  apt: update_cache=yes

- name: Install required packages
  apt: 
    pkg:
      - build-essential
      - libssl-dev
      - uuid-dev
      - squashfs-tools
      - libseccomp-dev
      - pkg-config
    state: present

- name: Download, Untar and install go
  unarchive:
    src: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
    dest: /usr/local/
    copy: no

- name: Adding go to the PATH
  shell: echo 'export PATH=/usr/local/go/bin:${PATH}' >> ~/.bashrc

# The syngulairty source is build in home and instaled in /usr/local
# when we need to uninstall singulairty we will need the build folder
# in ~/singularity
- name: Clone singularity source form Git 
  git:
    repo: https://github.com/sylabs/singularity.git
    dest: ~/singularity/src/github.com/sylabs

# - name: Setting up environment for go
#   shell: "{{ item }}"
#   with_items:
#     - echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
#     - echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
#     - source ~/.bashrc

# - name: Create singularity install dir
#   file: 
#   $ mkdir -p $GOPATH/src/github.com/sylabs
# $ cd $GOPATH/src/github.com/sylabs
# $ git clone https://github.com/sylabs/singularity.git
# $ cd singularity